### ISSUE TITLE
any implementations of "gateway"-like two-way relay?

### ISSUE THREAD

**Issue by lagleki** [go-chat-bot/plugins#26]
I'd like to have a relay between Slack/Telegram/IRC for all messages sent to/from every network.
Is such plugin already available?

**Comment by fabioxgn** [comment]
@lagleki Hi.

Right now there's no way to do that. Each plugin is unaware of the current protocol. It receives a message and can responto to it. This kind of feature would have to be implemented on the bot, which is also unaware of the protocols: https://github.com/go-chat-bot/bot

I guess that the simplest way to implement this would be to add a new event that broadcasts all messages and in this event you could implement this relay.

If I have some free time toda I'll try to implement it, it shouldn't be hard.

**Comment by imarsman** [comment]
Hello. Looks like a great project. Thank-you! Would a plugin triggered by an empty string instead of, say "hello" catch all messages? I am interested in writing a plugin that takes messages and archives them.

**Comment by fabioxgn** [comment]
@imarsman for that you just need to implement a `PassiveCommand` function, please, take a look at this: https://github.com/go-chat-bot/plugins/blob/master/chucknorris/chucknorris.go#L83

This plugin replies with a chuck norris quote each time someone mentions chuck, or norris, etc.

Basically you just need to do this:

```Go
func archiver(command *bot.PassiveCmd) (string, error) {
	archiveMyStuff(command.Raw);
	return "", nil
}

func init() {
	bot.RegisterPassiveCommand(
		"archiver",
		archiver)
}
```

**Comment by imarsman** [comment]
Ok, so would an init work like this?

func init() {
	bot.RegisterPassiveCommand(
		"",
		archiver)
}

**Comment by imarsman** [comment]
I apologize, I see what you meant.
