### ISSUE TITLE
How would one make a Channel logger?

### ISSUE THREAD

**Issue by FilBot3** [go-chat-bot/plugins#29]
How would one make a channel logger using this plugin system? Most of these seem to be driven off keywords, or the `!` prefix for commands. I guess an example of an echo plugin without using the keyword echo would work.

**Comment by fabioxgn** [comment]
To implement a logger, just implement a passive plugin, look at this one for an example:

https://github.com/go-chat-bot/plugins/blob/master/catfacts/catfacts.go#L25

This catfacts plugin says a random fact about cats every time some words like cat, ou cats are said on a channel.

A passive command will receive all the messages in a channel, then you can log it as you like.
