### ISSUE TITLE
cmd plugin is a horrific security hole

### ISSUE THREAD

**Issue by hashworks** [go-chat-bot/plugins#31]
It has zero authentication, and even if it had I wouldn't trust it. Unexperienced users could use this plugin in their channels without giving it another thought. IMO this is simply a good way to open systems to the world.

You should either add a huge warning or remove it.

**Comment by fabioxgn** [comment]
@hashworks no plugins are enabled by default in the bot.

You have to import it in your bot for it to be compiled and enabled, but maybe putting a README with a security warning on it's folder might clarify this.
