### ISSUE TITLE
JIRA plugin improvement suggestions

### ISSUE THREAD

**Issue by sochotnicky** [go-chat-bot/plugins#33]
Right now JIRA plugin is just outputting "full" URL to the issue.

What I imagine would be a bit more useful is:
 * actually checking that the issue is real in the configured JIRA instance (instead of relying on regexp)
 * ability to output pieces of JIRA info (summary, issue type, assignee etc)
 * configurability of above per-channel
 * notifications when new issues get created (again mapping which channels get which project updates)

I'd be more than happy to take this as a side project. Just wanted to gauge whether this would be acceptable (since it would definitely make the plugin more complex and pull in some more deps).

**Comment by fabioxgn** [comment]
@sochotnicky this JIRA plugin is very simple so I don't think many people use it. I'm ok to merge your changes if it makes the plugin better, just send a PR.

**Comment by sochotnicky** [comment]
I'll close this - there's more PRs planned but we can work on this piece by piece.

Thanks again for reviews!
