### ISSUE TITLE
[n00b q] custom plugin compiles but doesn't load

### ISSUE THREAD

**Issue by zuccon** [go-chat-bot/plugins#48]
Hello and sorry for the n00b question, I just started with golang so I'm surely doing something wrong with imports.

I'm trying to write a custom plugin. I used the snippet in the example and put it in `$GOROOT/src/zuccon/go-chat-bot-plugins/example/hello.go`

Just to be sure this is the contents:
```Go
package example

import (
	"fmt"

	"github.com/go-chat-bot/bot"
)

func hello(command *bot.Cmd) (msg string, err error) {
	msg = fmt.Sprintf("Hello %s", command.User.RealName)
	return
}

func init() {
	bot.RegisterCommand(
		"hello",
		"Sends a 'Hello' message to you on the channel.",
		"",
		hello)
}
```

I'm using the debug mode described in https://github.com/go-chat-bot/bot but I post here since it's related to plugins.

My `debug/main.go` import section looks like this:

```Go
import (
	"bufio"
	"fmt"
	"os"

	"github.com/go-chat-bot/bot"
	_ "zuccon/go-chat-bot-plugins/example"
)
```

But when I build and start the bot, I don't see any commands registered:
```
$ go build
$ ./debug 
Type a command or !help for available commands...
!help
bot: Type: '!help <command>' to see details about a specific command.
bot: Available commands: 
```

Is there anything obvious I'm doing wrong?

**Comment by fabioxgn** [comment]
Everything looks fine to me, are you sure that the package is loading? If I recall correctly the package name must match the directory name, and you package is `example` but your directory is `hello`, try renaming the package to `hello` to see if it helps.

**Comment by zuccon** [comment]
I followed the same logic used in this repo where the directory is called `example` and the filenames are arbitrary, the package is already in the `examples` directory in a file called `hello.go`.

Is there a way to verify that the package is loading, more debug from the bot maybe?

I know that if compiles it because when I add syntax errors I can see them while running `debug`.

**Comment by zuccon** [comment]
Turns out my setup was messed! I fixed it. Thanks for the help, and for this nice bot! If I ever make a useful plugin I'll ping you :)
